version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: orchid-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - orchid

  # Nginx Service
  web:
    image: nginx:1.25
    container_name: orchid-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - orchid
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: orchid-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: orchid
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: orchid
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - orchid-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - orchid

  # Valkey Service (Redis fork)
  valkey:
    image: valkey/valkey:latest
    container_name: orchid-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - orchid-valkey:/data
    networks:
      - orchid

networks:
  orchid:
    driver: bridge

volumes:
  orchid-mysql:
    driver: local
  orchid-valkey:
    driver: local